# Read and write data

In the exercise 'data manipulation' we have **read** data from a CSV file into our script. Similarly we can also **write** code outputs to file.   

```{block2, type = 'rmdtip'}

In this lesson you will learn to read and write plain-text and spatial vector file formats. Moreover, we will retrieve online data by means of a data API.

```

## Read/write tabular data

A series of formats are based on plain-text files.

For instance...

- comma-separated values files `.csv`
- semi-colon-separated values files `.csv`
- tab-separated values files `.tsv`
- other formats using custom delimiters
- fix-width files `.fwf`

The [`readr` library](https://readr.tidyverse.org/){target="_blank"} (also part of Tidyverse) provides a series of functions that can be used to load from and save to such data formats. For instance, the `read_csv` function reads a comma delimited (CSV) file from the path provided as the first argument. 

The code example below reads a CSV file that contains global fishery statistics provided by the [World Bank](https://datacatalog.worldbank.org/dataset/world-development-indicators){target="_blank"} and queries Norwegian entries. The function `writes_csv`  writes these entries to a new CSV file.  

```{r, echo=TRUE, message=FALSE, warning = FALSE}

library(tidyverse)

fishery_data <- readr::read_csv("data/capture-fisheries-vs-aquaculture.csv")
#print(fishery_data)

#print(typeof(fishery_data$))

fishery_data %>%
  dplyr::filter(Entity == "Norway") %>%
  readr::write_csv("data/capture-fisheries-vs-aquaculture-noraway.csv", append=FALSE) %>%
  
  dplyr::slice_head(n = 3) %>%
  knitr::kable()
  
```

In order to run the script, [download the CSV file](data/capture-fisheries-vs-aquaculture.csv){target="_blank"}. Then copy and run the code in a new R-script.

## Comma Separated Values

The file `2011_OAC_supgrp_Leicester.csv` contains

- one row for each [Output Area (OA)](https://www.ons.gov.uk/methodology/geography/ukgeographies/censusgeography) in Leicester
- [Lower-Super Output Area (LSOA)](https://www.ons.gov.uk/methodology/geography/ukgeographies/censusgeography) containing the OA
- code and name of the supergroup assigned to the OA by the [2011 Output Area Classification](http://geogale.github.io/2011OAC/)
- total population of the OA

Extract showing only the first few rows

```{}
OA11CD,LSOA11CD,supgrpcode,supgrpname,Total_Population
E00069517,E01013785,6,Suburbanites,313
E00069514,E01013784,2,Cosmopolitans,323
E00169516,E01013713,4,Multicultural Metropolitans,341
E00169048,E01032862,4,Multicultural Metropolitans,345
```



## readr

The [`readr`](https://readr.tidyverse.org/) (pronounced *read-er*) library is part of [`tidyverse`](https://www.tidyverse.org/)

Provides functions to read and write text files

- `readr::read_csv`: comma-separated files `.csv`
- `readr::read_csv2`: semi-colon-separated files `.csv`
- `readr::read_tsv`: tab-separated files `.tsv`
- `readr::read_fwf`: fix-width files `.fwf`
- `readr::read_delim`: files using a custom delimiter

and their *write* counterpart, such as

- `readr::write_csv`: comma-separated files `.csv`


## readr::read_csv

The `readr::read_csv` function of the [`readr`](https://readr.tidyverse.org/index.html) library reads a *csv* file from the path provided as the first argument



## Read options

Read functions provide options about how to interpret a file contents

- For instance, `readr::read_csv`
  - `col_names`: 
    - `TRUE` or `FALSE` whether top row is column names
    - or a vector of column names
  - `col_types`:
    - a `cols()` specification or a string
  - `skip`: lines to skip before reading data
  - `n_max`: max number of record to read



## Column specifications

- `col_logical()` or `l` as logic values
- `col_integer()` or `i` as integer
- `col_double()` or `d` as numeric (double)
- `col_character()` or `c` as character
- `col_factor(levels, ordered)` or `f` as factor
- `col_date(format = "")` or `D` as data type
- `col_time(format = "")` or `t` as time type
- `col_datetime(format = "")` or `T` as datetime
- `col_number()` or `n` as numeric (dropping marks)
- `col_skip()` or `_` or `-` don’t import
- `col_guess()` or `?` use best type based on the input



## readr::read_csv

Using `readr::read_csv` as in the previous example with no further options will generate the following warning




## readr::read_csv


## readr::read_csv



## readr::write_csv

The function `write_csv` can be used to save a dataset to `csv`

Example:

1. **read** the 2011 OAC dataset
2. **select** a few columns
3. **filter** only those OA in the supergroup *Suburbanites* (code `6`)
4. **write** the results to a file named *2011_OAC_supgrp_Leicester_supgrp6.csv*





## readr::write_tsv




## Other data imports

[Tidyverse](https://www.tidyverse.org/) also imports [other packages for reading data](https://www.tidyverse.org/packages/#import)

- Tabular formats
  - [`readxl`](https://readxl.tidyverse.org/) for Excel (`.xls` and `.xlsx`)
  - [`haven`](https://haven.tidyverse.org/) for SPSS, Stata, and SAS data.
- Databases
  - [`DBI`](https://cran.r-project.org/web/packages/DBI/) for relational databases
- NoSQL
  - [`jsonlite`](https://cran.r-project.org/web/packages/jsonlite/) for JSON
  - [`xml2`](https://cran.r-project.org/web/packages/xml2/) for XML
- Web
  - [`httr`](https://cran.r-project.org/web/packages/httr/) for web APIs

<!--
  - Specific backends require different packages, e.g. [`RPostgreSQL`](https://cran.r-project.org/web/packages/RPostgreSQL/)
  - [`rvest`](https://cran.r-project.org/web/packages/rvest/) for web scraping.
-->



## Read/write spatial data

retires 2023: https://cran.r-project.org/web/packages/maptools/index.html
maptools und readShapePoints

GDAL: https://cran.r-project.org/web/packages/sf/vignettes/sf2.html

aspace retired. https://rdrr.io/cran/aspace/

