# Selection and filtering

all R code parts are removed, because of an unsolved error message


## Recap

**Prev**: Data Frames

- Data Frames
- Tibbles

**Now**: Data selection and filtering

- dplyr
- dplyr::select
- dplyr::filter



## dplyr

The `dplyr` (pronounced *dee-ply-er*) library is part of `tidyverse` and it offers a grammar for data manipulation

- `select`: select specific columns
- `filter`: select specific rows
- `arrange`: arrange rows in a particular order
- `summarise`: calculate aggregated values (e.g., mean, max, etc)
- `group_by`: group data based on common column values
- `mutate`: add columns
- `join`: merge tables (`tibbles` or `data.frames`)




## Example dataset



## Selecting table columns



## dplyr::select

`select` can be used to specify which columns to retain



## dplyr::select

... or whichones to drop, using - in front of the column name


## Logical filtering

Conditional statements can be used to filter a vector

- i.e. to retain only certain values
- where the specified value is `TRUE`



## Conditional filtering

As a conditional expression results in a logic vector...


... conditional expressions can be used for filtering



## Filtering data frames

The same approach can be applied to **data frames** and **tibbles**



## dplyr::filter



## Select and filter



## Summary

Data selection and filtering

- dplyr
- dplyr::select
- dplyr::filter




