# Data visualisation

all R code parts are removed, because of an unsolved error message


## Recap

**Prev**: Reproducibility

- 221 Reproducibility
- 222 R and Markdown
- 223 Git
- 224 Practical session

**Now**: Data visualisation

- Grammar of graphics
- ggplot2


## Visual variables

A **visual variable** is an aspect of a **mark** that can be controlled to change its appearance. 

Visual variables include: 

- Size
- Shape 
- Orientation
- Colour (hue)
- Colour value (brightness)
- Texture
- Position (2 dimensions)


## Grammar of graphics

Grammars provide rules for languages

*"The grammar of graphics takes us beyond a limited set of charts (words) to an almost unlimited world of graphical forms (statements)"* (Wilkinson, 2005)

Statistical graphic specifications are expressed in six statements:

1. **Data** manipulation 
2. **Variable** transformations (e.g., rank),
3. **Scale** transformations (e.g., log),
4. **Coordinate system** transformations (e.g., polar),
5. **Element**: mark (e.g., points) and visual variables (e.g., color)
6. **Guides** (axes, legends, etc.).


## ggplot2

The `ggplot2` library offers a series of functions for creating graphics **declaratively**, based on the Grammar of Graphics. 

To create a graph in `ggplot2`:

- provide the data
- specify elements
    - which visual variables (`aes`)
    - which marks (e.g., `geom_point`)
- apply transformations
- guides



## Boxplots

- `x` categorical variable
- `y` variable to plot
- `geom_boxplot`






## Jittered points

- `x` categorical variable
- `y` variable to plot
- `geom_jitter`





## Violin plot

- `x` categorical variable
- `y` variable to plot
- `geom_violin`




## Violin plot




## Lines

- `x` e.g., a temporal variable
- `y` variable to plot
- `geom_line`




## Lines





## Scatterplots

- `x` and `y` variable to plot
- `geom_point`





## Overlapping points

- `x` and `y` variable to plot
- `geom_count` counts overlapping points and maps the count to size




## Overlapping points



## Bin counts

- `x` and `y` variable to plot
- `geom_bin2d`


## Bin counts





## Summary

Data visualisation

- Grammar of graphics
- ggplot2

**Next**: Descriptive statistics

- stat.desc
- dplyr::across

