project:
  type: book

  output-dir: docs
  resources:
    # Automatically include static files like images, CSS, JS
    - "*.png"
    - "*.jpg"
    - "*.jpeg"
    - "*.js"
    - "*.html"
    - "*.css"
    - "*.gitkeep"
    - ".nojekyll" # Prevents Jekyll processing on GitHub Pages

book:
  title: "Automated Data Processing with R"
  author: "Christian Neuwirth & Maximilian Elixhauser"
  date: last-modified
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-core-concepts.qmd
    - 03-data-structures.qmd
    - 04-spatial-data-structures.qmd
    - 05-control-structures.qmd
    - 06-functions.qmd
    - 07-data-manipulation.qmd
    - 08-read-write.qmd
    - 09-spatial-data-manipulation.qmd
    - 10-data-viz.qmd
    - 11-quarto.qmd
    - references.qmd
  page-navigation: true

  page-footer:
    center: "Copyright ©, UNIGIS Salzburg"

  sidebar:
    search: true
    logo: "branding/UNIGIS_Salzburg_Schriftlogo_v05.png"
    logo-href: "https://unigis.at/"

bibliography: references.bib

format:
  html:
    css: css/custom.css
    theme:
      - cosmo
      - css/theme.scss
    # Set this based on the module language:
    # toc-title: "Lektionsinhalt" # ← Uncomment for German
    toc-title: "Lesson Content" # ← Default for English
    toc: true
    toc-location: right
    toc-depth: 3
    code-fold: false
    highlight: github
    code-link: true
    html-math-method: katex
    smooth-scroll: true

build:
  commands:
    - quarto render --to html

custom-callout:
  exercisebox:
    icon: true
  assignmentbox:
    icon: true

editor: source
lang: en

language:
  en:
    callout-tip-title: "Learning Objectives"
    callout-note-title: "Note"
  de:
    callout-tip-title: "Lernziele"
    callout-note-title: "Hinweis"

filters:
  - webr # a extension which allows to run R code in a web browser
  - custom-callout # a extension which allows to create custom callouts
