<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lesson 4 Spatial Data Structures | Automated Data Processing with R</title>
  <meta name="description" content="BookDown materials for the UNIGIS module Application Development - Introduction to R." />
  <meta name="generator" content="bookdown 0.29 and GitBook 2.6.7" />

  <meta property="og:title" content="Lesson 4 Spatial Data Structures | Automated Data Processing with R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/branding/Cover_epub.png" />
  <meta property="og:description" content="BookDown materials for the UNIGIS module Application Development - Introduction to R." />
  <meta name="github-repo" content="UNIGIS-Salzburg/En_AppDev-R" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lesson 4 Spatial Data Structures | Automated Data Processing with R" />
  
  <meta name="twitter:description" content="BookDown materials for the UNIGIS module Application Development - Introduction to R." />
  <meta name="twitter:image" content="/branding/Cover_epub.png" />

<meta name="author" content="Christian Neuwirth &amp; Maximilian Elixhauser" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="branding/favicon.ico" type="image/x-icon" />
<link rel="prev" href="data-structures.html"/>
<link rel="next" href="control-structures.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.1.1/leaflet.js"></script>
<script src="libs/leaflet-providers-1.9.0/leaflet-providers_1.9.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.1.1/leaflet-providers-plugin.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="css/custom.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="https://unigis.at/en" target="_blank"><img alt="UNIGIS Salzburg" src="branding/UNIGIS_Salzburg_Schriftlogo_globe.png" width=100%></a></li>
<li><a href="./">Automated Data Processing with R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#about-this-module"><i class="fa fa-check"></i><b>1.1</b> About this module</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#r-programming-language"><i class="fa fa-check"></i><b>1.2</b> R programming language</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#installation-and-setup"><i class="fa fa-check"></i><b>1.3</b> Installation and Setup</a></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#interpreting-values"><i class="fa fa-check"></i><b>1.4</b> Interpreting values</a></li>
<li class="chapter" data-level="1.5" data-path="intro.html"><a href="intro.html#simple-data-types"><i class="fa fa-check"></i><b>1.5</b> Simple data types</a></li>
<li class="chapter" data-level="1.6" data-path="intro.html"><a href="intro.html#numop"><i class="fa fa-check"></i><b>1.6</b> Numeric operators</a></li>
<li class="chapter" data-level="1.7" data-path="intro.html"><a href="intro.html#logical-operators"><i class="fa fa-check"></i><b>1.7</b> Logical operators</a></li>
<li class="chapter" data-level="1.8" data-path="intro.html"><a href="intro.html#references"><i class="fa fa-check"></i><b>1.8</b> References</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="core.html"><a href="core.html"><i class="fa fa-check"></i><b>2</b> Core concepts</a>
<ul>
<li class="chapter" data-level="2.1" data-path="core.html"><a href="core.html#variables"><i class="fa fa-check"></i><b>2.1</b> Variables</a></li>
<li class="chapter" data-level="2.2" data-path="core.html"><a href="core.html#algorithms-and-functions"><i class="fa fa-check"></i><b>2.2</b> Algorithms and functions</a></li>
<li class="chapter" data-level="2.3" data-path="core.html"><a href="core.html#libraries"><i class="fa fa-check"></i><b>2.3</b> Libraries</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-structures.html"><a href="data-structures.html"><i class="fa fa-check"></i><b>3</b> Data Structures</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-structures.html"><a href="data-structures.html#vectors"><i class="fa fa-check"></i><b>3.1</b> Vectors</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data-structures.html"><a href="data-structures.html#vector-element-selection"><i class="fa fa-check"></i><b>3.1.1</b> Vector element selection</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-structures.html"><a href="data-structures.html#functions-on-vectors"><i class="fa fa-check"></i><b>3.1.2</b> Functions on vectors</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-structures.html"><a href="data-structures.html#multi-dimensional-data-types"><i class="fa fa-check"></i><b>3.2</b> Multi-dimensional data types</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="data-structures.html"><a href="data-structures.html#matrices"><i class="fa fa-check"></i><b>3.2.1</b> Matrices</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-structures.html"><a href="data-structures.html#arrays"><i class="fa fa-check"></i><b>3.2.2</b> Arrays</a></li>
<li class="chapter" data-level="3.2.3" data-path="data-structures.html"><a href="data-structures.html#selection"><i class="fa fa-check"></i><b>3.2.3</b> Selection</a></li>
<li class="chapter" data-level="3.2.4" data-path="data-structures.html"><a href="data-structures.html#list"><i class="fa fa-check"></i><b>3.2.4</b> List</a></li>
<li class="chapter" data-level="3.2.5" data-path="data-structures.html"><a href="data-structures.html#data-frame"><i class="fa fa-check"></i><b>3.2.5</b> Data Frame</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="spatial-data-structures.html"><a href="spatial-data-structures.html"><i class="fa fa-check"></i><b>4</b> Spatial Data Structures</a>
<ul>
<li class="chapter" data-level="4.1" data-path="spatial-data-structures.html"><a href="spatial-data-structures.html#vector-data-structures"><i class="fa fa-check"></i><b>4.1</b> Vector Data Structures</a></li>
<li class="chapter" data-level="4.2" data-path="spatial-data-structures.html"><a href="spatial-data-structures.html#raster-data-structures"><i class="fa fa-check"></i><b>4.2</b> Raster Data Structures</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="spatial-data-structures.html"><a href="spatial-data-structures.html#working-with-spatraster-objects"><i class="fa fa-check"></i><b>4.2.1</b> Working with SpatRaster objects</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="control-structures.html"><a href="control-structures.html"><i class="fa fa-check"></i><b>5</b> Control structures</a>
<ul>
<li class="chapter" data-level="5.1" data-path="control-structures.html"><a href="control-structures.html#if"><i class="fa fa-check"></i><b>5.1</b> If</a></li>
<li class="chapter" data-level="5.2" data-path="control-structures.html"><a href="control-structures.html#else"><i class="fa fa-check"></i><b>5.2</b> Else</a></li>
<li class="chapter" data-level="5.3" data-path="control-structures.html"><a href="control-structures.html#code-blocks"><i class="fa fa-check"></i><b>5.3</b> Code blocks</a></li>
<li class="chapter" data-level="5.4" data-path="control-structures.html"><a href="control-structures.html#loops"><i class="fa fa-check"></i><b>5.4</b> Loops</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="control-structures.html"><a href="control-structures.html#while-and-repeat"><i class="fa fa-check"></i><b>5.4.1</b> While and repeat</a></li>
<li class="chapter" data-level="5.4.2" data-path="control-structures.html"><a href="control-structures.html#for"><i class="fa fa-check"></i><b>5.4.2</b> For</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="control-structures.html"><a href="control-structures.html#loops-with-conditional-statements"><i class="fa fa-check"></i><b>5.5</b> Loops with conditional statements</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="control-structures.html"><a href="control-structures.html#exercise-loops-with-conditional-statements"><i class="fa fa-check"></i><b>5.5.1</b> Exercise: loops with conditional statements</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>6</b> Functions</a>
<ul>
<li class="chapter" data-level="6.1" data-path="functions.html"><a href="functions.html#defining-functions"><i class="fa fa-check"></i><b>6.1</b> Defining functions</a></li>
<li class="chapter" data-level="6.2" data-path="functions.html"><a href="functions.html#more-parameters"><i class="fa fa-check"></i><b>6.2</b> More parameters</a></li>
<li class="chapter" data-level="6.3" data-path="functions.html"><a href="functions.html#more-return-values"><i class="fa fa-check"></i><b>6.3</b> More return values</a></li>
<li class="chapter" data-level="6.4" data-path="functions.html"><a href="functions.html#functions-and-control-structures"><i class="fa fa-check"></i><b>6.4</b> Functions and control structures</a></li>
<li class="chapter" data-level="6.5" data-path="functions.html"><a href="functions.html#scope"><i class="fa fa-check"></i><b>6.5</b> Scope</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="data-manipulation.html"><a href="data-manipulation.html"><i class="fa fa-check"></i><b>7</b> Data manipulation</a>
<ul>
<li class="chapter" data-level="7.1" data-path="data-manipulation.html"><a href="data-manipulation.html#preparation"><i class="fa fa-check"></i><b>7.1</b> Preparation</a></li>
<li class="chapter" data-level="7.2" data-path="data-manipulation.html"><a href="data-manipulation.html#data-manipulation-1"><i class="fa fa-check"></i><b>7.2</b> Data manipulation</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="data-manipulation.html"><a href="data-manipulation.html#summarise"><i class="fa fa-check"></i><b>7.2.1</b> Summarise</a></li>
<li class="chapter" data-level="7.2.2" data-path="data-manipulation.html"><a href="data-manipulation.html#select-and-filter"><i class="fa fa-check"></i><b>7.2.2</b> Select and filter</a></li>
<li class="chapter" data-level="7.2.3" data-path="data-manipulation.html"><a href="data-manipulation.html#mutate"><i class="fa fa-check"></i><b>7.2.3</b> Mutate</a></li>
<li class="chapter" data-level="7.2.4" data-path="data-manipulation.html"><a href="data-manipulation.html#arrange"><i class="fa fa-check"></i><b>7.2.4</b> Arrange</a></li>
<li class="chapter" data-level="7.2.5" data-path="data-manipulation.html"><a href="data-manipulation.html#exercise-data-manipulation"><i class="fa fa-check"></i><b>7.2.5</b> Exercise: data manipulation</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="data-manipulation.html"><a href="data-manipulation.html#join"><i class="fa fa-check"></i><b>7.3</b> Join</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="data-manipulation.html"><a href="data-manipulation.html#exercise-join"><i class="fa fa-check"></i><b>7.3.1</b> Exercise: join</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html"><i class="fa fa-check"></i><b>8</b> Spatial Data Manipulation</a>
<ul>
<li class="chapter" data-level="8.1" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#introduction"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#spatial-aggregation"><i class="fa fa-check"></i><b>8.2</b> Spatial Aggregation</a></li>
<li class="chapter" data-level="8.3" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#merging-and-appending-spatial-data"><i class="fa fa-check"></i><b>8.3</b> Merging and Appending Spatial Data</a></li>
<li class="chapter" data-level="8.4" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#handling-missing-data"><i class="fa fa-check"></i><b>8.4</b> Handling Missing Data</a></li>
<li class="chapter" data-level="8.5" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#spatial-data-cleaning"><i class="fa fa-check"></i><b>8.5</b> Spatial Data Cleaning</a></li>
<li class="chapter" data-level="8.6" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#multidimensional-data-wrangling-with-stars"><i class="fa fa-check"></i><b>8.6</b> Multidimensional Data Wrangling with stars</a></li>
<li class="chapter" data-level="8.7" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#challenges-in-spatial-data-structures"><i class="fa fa-check"></i><b>8.7</b> Challenges in Spatial Data Structures</a></li>
<li class="chapter" data-level="8.8" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#dealing-with-large-spatial-datasets."><i class="fa fa-check"></i><b>8.8</b> Dealing with large spatial datasets.</a></li>
<li class="chapter" data-level="8.9" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#case-study-a-complete-spatial-data-wrangling-workflow"><i class="fa fa-check"></i><b>8.9</b> Case Study: A Complete Spatial Data Wrangling Workflow</a></li>
<li class="chapter" data-level="8.10" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#introduction-1"><i class="fa fa-check"></i><b>8.10</b> Introduction</a></li>
<li class="chapter" data-level="8.11" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#filtering-spatial-data"><i class="fa fa-check"></i><b>8.11</b> Filtering Spatial Data</a></li>
<li class="chapter" data-level="8.12" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#filtering-rasters-with-terra"><i class="fa fa-check"></i><b>8.12</b> Filtering Rasters with terra</a></li>
<li class="chapter" data-level="8.13" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#spatial-joins-with-sf-though..-we-could-also-put-that-in-chapter-10-and-make-12-bigger-with-spatial-stat"><i class="fa fa-check"></i><b>8.13</b> Spatial Joins with sf (though.. we could also put that in Chapter 10 and make 12 bigger with spatial stat)</a></li>
<li class="chapter" data-level="8.14" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#geometric-operations-with-sf"><i class="fa fa-check"></i><b>8.14</b> Geometric Operations with sf</a>
<ul>
<li class="chapter" data-level="8.14.1" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#intersect"><i class="fa fa-check"></i><b>8.14.1</b> Intersect</a></li>
<li class="chapter" data-level="8.14.2" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#buffer"><i class="fa fa-check"></i><b>8.14.2</b> Buffer</a></li>
<li class="chapter" data-level="8.14.3" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#union-and-difference"><i class="fa fa-check"></i><b>8.14.3</b> Union and Difference</a></li>
</ul></li>
<li class="chapter" data-level="8.15" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#coordinate-transformations-and-reprojections-with-sf-and-terra"><i class="fa fa-check"></i><b>8.15</b> Coordinate Transformations and Reprojections with sf and terra</a></li>
<li class="chapter" data-level="8.16" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#raster-operations-with-terra"><i class="fa fa-check"></i><b>8.16</b> Raster Operations with terra</a>
<ul>
<li class="chapter" data-level="8.16.1" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#resampling"><i class="fa fa-check"></i><b>8.16.1</b> Resampling</a></li>
<li class="chapter" data-level="8.16.2" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#raster-algebra"><i class="fa fa-check"></i><b>8.16.2</b> Raster Algebra</a></li>
</ul></li>
<li class="chapter" data-level="8.17" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#applied-spatial-statistics-with-spatstat"><i class="fa fa-check"></i><b>8.17</b> Applied Spatial Statistics with spatstat</a></li>
<li class="chapter" data-level="8.18" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#comparative-analysis-of-packages"><i class="fa fa-check"></i><b>8.18</b> Comparative Analysis of Packages</a></li>
<li class="chapter" data-level="8.19" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#exercise"><i class="fa fa-check"></i><b>8.19</b> Exercise</a></li>
<li class="chapter" data-level="8.20" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#topological-relationships"><i class="fa fa-check"></i><b>8.20</b> Topological Relationships</a>
<ul>
<li class="chapter" data-level="8.20.1" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#resampling-raster-data-in-terra"><i class="fa fa-check"></i><b>8.20.1</b> Resampling Raster Data in Terra</a></li>
<li class="chapter" data-level="8.20.2" data-path="spatial-data-manipulation.html"><a href="spatial-data-manipulation.html#basic-raster-operations"><i class="fa fa-check"></i><b>8.20.2</b> Basic Raster Operations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="read-and-write-data.html"><a href="read-and-write-data.html"><i class="fa fa-check"></i><b>9</b> Read and write data</a>
<ul>
<li class="chapter" data-level="9.1" data-path="read-and-write-data.html"><a href="read-and-write-data.html#read-and-write-tabular-data"><i class="fa fa-check"></i><b>9.1</b> Read and write tabular data</a></li>
<li class="chapter" data-level="9.2" data-path="read-and-write-data.html"><a href="read-and-write-data.html#read-and-write-vector-data"><i class="fa fa-check"></i><b>9.2</b> Read and write vector data</a></li>
<li class="chapter" data-level="9.3" data-path="read-and-write-data.html"><a href="read-and-write-data.html#read-and-write-raster-data"><i class="fa fa-check"></i><b>9.3</b> Read and write raster data</a></li>
<li class="chapter" data-level="9.4" data-path="read-and-write-data.html"><a href="read-and-write-data.html#data-api"><i class="fa fa-check"></i><b>9.4</b> Data API</a></li>
<li class="chapter" data-level="9.5" data-path="read-and-write-data.html"><a href="read-and-write-data.html#additional-thoughts-so-far-for-revision"><i class="fa fa-check"></i><b>9.5</b> Additional Thoughts so far for revision</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="read-and-write-data.html"><a href="read-and-write-data.html#advanced-json-handling-with-httr2"><i class="fa fa-check"></i><b>9.5.1</b> <strong>7.4 Advanced JSON Handling with <code>httr2</code></strong></a></li>
<li class="chapter" data-level="9.5.2" data-path="read-and-write-data.html"><a href="read-and-write-data.html#caching-data-with-httr2"><i class="fa fa-check"></i><b>9.5.2</b> <strong>7.5 Caching Data with <code>httr2</code></strong></a></li>
<li class="chapter" data-level="9.5.3" data-path="read-and-write-data.html"><a href="read-and-write-data.html#error-handling-and-retries-with-httr2"><i class="fa fa-check"></i><b>9.5.3</b> <strong>7.6 Error Handling and Retries with <code>httr2</code></strong></a></li>
<li class="chapter" data-level="9.5.4" data-path="read-and-write-data.html"><a href="read-and-write-data.html#advanced-api-techniques"><i class="fa fa-check"></i><b>9.5.4</b> <strong>7.7 Advanced API Techniques</strong></a></li>
<li class="chapter" data-level="9.5.5" data-path="read-and-write-data.html"><a href="read-and-write-data.html#introduction-to-web-scraping-altough-this-might-be-too-much..-and-even-if-its-important-for-data-sourcing-its-kind-of-a-grey-area-limited-by-rate-limits-or-considerations-with-tos."><i class="fa fa-check"></i><b>9.5.5</b> <strong>7.8 Introduction to Web Scraping</strong> (Altough, this might be too much.. and even if it’s important, for data sourcing, it’s kind of a grey area, limited by rate limits or considerations with ToS.)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="data-visualization.html"><a href="data-visualization.html"><i class="fa fa-check"></i><b>10</b> Data visualization</a>
<ul>
<li class="chapter" data-level="10.1" data-path="data-visualization.html"><a href="data-visualization.html#the-grammar-of-graphics"><i class="fa fa-check"></i><b>10.1</b> The Grammar of Graphics</a></li>
<li class="chapter" data-level="10.2" data-path="data-visualization.html"><a href="data-visualization.html#visualization-of-distributions"><i class="fa fa-check"></i><b>10.2</b> Visualization of distributions</a></li>
<li class="chapter" data-level="10.3" data-path="data-visualization.html"><a href="data-visualization.html#boxplots"><i class="fa fa-check"></i><b>10.3</b> Boxplots</a></li>
<li class="chapter" data-level="10.4" data-path="data-visualization.html"><a href="data-visualization.html#scatterplots"><i class="fa fa-check"></i><b>10.4</b> Scatterplots</a></li>
<li class="chapter" data-level="10.5" data-path="data-visualization.html"><a href="data-visualization.html#map-visualization"><i class="fa fa-check"></i><b>10.5</b> Map visualization</a></li>
<li class="chapter" data-level="10.6" data-path="data-visualization.html"><a href="data-visualization.html#interactive-maps"><i class="fa fa-check"></i><b>10.6</b> Interactive Maps</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="r-markdown.html"><a href="r-markdown.html"><i class="fa fa-check"></i><b>11</b> R Markdown</a>
<ul>
<li class="chapter" data-level="11.1" data-path="r-markdown.html"><a href="r-markdown.html#set-up-your-work-environment"><i class="fa fa-check"></i><b>11.1</b> Set up your work environment</a></li>
<li class="chapter" data-level="11.2" data-path="r-markdown.html"><a href="r-markdown.html#create-a-local-clone"><i class="fa fa-check"></i><b>11.2</b> Create a local clone</a></li>
<li class="chapter" data-level="11.3" data-path="r-markdown.html"><a href="r-markdown.html#create-a-first-rmarkdown-document"><i class="fa fa-check"></i><b>11.3</b> Create a first RMarkdown document</a></li>
<li class="chapter" data-level="11.4" data-path="r-markdown.html"><a href="r-markdown.html#synchronize-with-github"><i class="fa fa-check"></i><b>11.4</b> Synchronize with GitHub</a></li>
<li class="chapter" data-level="11.5" data-path="r-markdown.html"><a href="r-markdown.html#basic-rmarkdown-syntax"><i class="fa fa-check"></i><b>11.5</b> Basic RMarkdown syntax</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="r-markdown.html"><a href="r-markdown.html#references-in-rmarkdown"><i class="fa fa-check"></i><b>11.5.1</b> References in RMarkdown</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="r-markdown.html"><a href="r-markdown.html#speed-up-your-workflows"><i class="fa fa-check"></i><b>11.6</b> Speed up your workflows</a></li>
<li class="chapter" data-level="11.7" data-path="r-markdown.html"><a href="r-markdown.html#self-study"><i class="fa fa-check"></i><b>11.7</b> Self-study</a></li>
</ul></li>
<li class="divider"></li>
<li>Copyright © UNIGIS Salzburg.</li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Automated Data Processing with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="spatial-data-structures" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Lesson 4</span> Spatial Data Structures<a href="spatial-data-structures.html#spatial-data-structures" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In the realm of geoinformatics, spatial data stands as a cornerstone, offering a lens through which we can view, analyze, and interpret the world around us. At this point in your Master’s, you are already familiar with the basic spatial entities of points, lines, and polygons. These fundamental structures, while simple in concept, form the bedrock of complex spatial analyses and visualizations.</p>
<p>R, with its rich ecosystem of packages, offers a unique perspective on spatial data. Packages like <strong>sf</strong>, <strong>terra</strong>, <strong>stars</strong>, and <strong>spatstat</strong> have been game-changers, allowing us to handle spatial vector, raster and multidimensional data with unprecedented ease and flexibility.</p>

<div class="rmdtip">
<p>In this lesson, you will get to know the following spatial data structures in R:</p>
<ol style="list-style-type: decimal">
<li>Vector data structures based on the simple feature specification implemented in package <a href="https://r-spatial.github.io/sf/" target="_blank">sf</a></li>
<li>Raster data structures as provided by the package <a href="https://rspatial.org/pkg/" target="_blank">terra</a></li>
</ol>
<p>You will also learn how to retrieve, assign, and modify coordinate systems, projections and transformations of spatial data structures.</p>
</div>
<div id="vector-data-structures" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Vector Data Structures<a href="spatial-data-structures.html#vector-data-structures" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Spatial data structures are the foundation upon which geospatial information is built. They provide a systematic framework for organizing and representing geographical entities, ensuring that they can be efficiently processed, analyzed, and visualized.</p>
<p>In this section, we will use the library <code>sf</code> to work with vector data structures. The name (sf stands for <strong>simple features</strong>) already implies that <code>sf</code> supports simple feature access via R. Simple features is a widely supported data model that underlies data structures in many GIS applications including QGIS and PostGIS. A major advantage of this is that using the data model ensures your work is cross-transferable to other set-ups, for example importing from and exporting to spatial databases.</p>
<p>Simple features have spatial, geometric attributes as well as non-spatial attributes. The most common geometry types are points, lines, and polygons and their respective “multi” versions (see <a href="https://r-spatial.github.io/sf/articles/sf1.html#simple-feature-geometry-types" target="_blank">Simple feature geometry types</a>).</p>
<p><strong>Points</strong> are fundamental in geospatial analysis. They are the simplest spatial entities, representing a singular location in space. They have no dimensions, meaning they don’t possess length, width, or area. Using the <code>sf</code> package, you can create and manipulate point data with ease:</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="spatial-data-structures.html#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a point</span></span>
<span id="cb92-2"><a href="spatial-data-structures.html#cb92-2" aria-hidden="true" tabindex="-1"></a>point <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_point</span>(<span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">5</span>))</span>
<span id="cb92-3"><a href="spatial-data-structures.html#cb92-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-4"><a href="spatial-data-structures.html#cb92-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to sf object</span></span>
<span id="cb92-5"><a href="spatial-data-structures.html#cb92-5" aria-hidden="true" tabindex="-1"></a>point_sf <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_sf</span>(<span class="at">geometry =</span> sf<span class="sc">::</span><span class="fu">st_sfc</span>(point))</span></code></pre></div>

<div class="rmdtip">
The operator :: is used to indicate that the functions <code>st_point</code>, <code>st_sf</code> and <code>st_sfc</code> are situated within the library <code>sf</code>. This helps avoiding ambiguities in the case functions from different loaded libraries have identical names.
</div>
<p>The function <code>st_point</code> creates a simple feature object from a numeric vector. The object is of the same nature as the numeric vector <code>c(5,5)</code>. To convert to an sf-object, the function <code>st_sf</code> is used.</p>
<p>Sf-objects are similar in structure as data frames. However, in contrast to data frames, sf-objects have an additional geometry column. The sf-object <code>point_sf</code> (created by the code above) contains a single point geometry and no fields:</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="spatial-data-structures.html#cb93-1" aria-hidden="true" tabindex="-1"></a>point_sf</span></code></pre></div>
<pre><code>## Simple feature collection with 1 feature and 0 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: 5 ymin: 5 xmax: 5 ymax: 5
## CRS:           NA
##      geometry
## 1 POINT (5 5)</code></pre>
<p>In principle sf-objects can be treated like data frames. Accordingly, data frame syntax is used to assign fields (table columns) to geometries:</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="spatial-data-structures.html#cb95-1" aria-hidden="true" tabindex="-1"></a>point_sf<span class="sc">$</span>name <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;my location&quot;</span>)</span></code></pre></div>
<p>To stay in GIS terms, records (rows) in a sf-object table may be called <code>features</code>. Features can be composed of multiple geometries:</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="spatial-data-structures.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create three points at locations 3/4, 5/3 and 7/1 as multipoint geometry</span></span>
<span id="cb96-2"><a href="spatial-data-structures.html#cb96-2" aria-hidden="true" tabindex="-1"></a>point_multi <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_multipoint</span>(<span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">1</span>), <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">2</span>)), <span class="at">dim =</span> <span class="st">&quot;XY&quot;</span>)</span>
<span id="cb96-3"><a href="spatial-data-structures.html#cb96-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-4"><a href="spatial-data-structures.html#cb96-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to sf object</span></span>
<span id="cb96-5"><a href="spatial-data-structures.html#cb96-5" aria-hidden="true" tabindex="-1"></a>point_sf_multi <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_sf</span>(<span class="at">geometry =</span> sf<span class="sc">::</span><span class="fu">st_sfc</span>(point_multi))</span>
<span id="cb96-6"><a href="spatial-data-structures.html#cb96-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-7"><a href="spatial-data-structures.html#cb96-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(point_sf_multi)</span></code></pre></div>
<p><img src="UNIGIS-AppDev-R_files/figure-html/unnamed-chunk-75-1.png" width="672" /></p>
<p>Plotting the metadata of sf-object <code>point_sf_multi</code> in the console reveals that <code>Geometry type</code> is <code>Multipoint</code> and that no coordinate reference system has been defined (<code>CRS: NA</code>):</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="spatial-data-structures.html#cb97-1" aria-hidden="true" tabindex="-1"></a>point_sf_multi</span></code></pre></div>
<pre><code>## Simple feature collection with 1 feature and 0 fields
## Geometry type: MULTIPOINT
## Dimension:     XY
## Bounding box:  xmin: 3 ymin: 1 xmax: 7 ymax: 4
## CRS:           NA
##                         geometry
## 1 MULTIPOINT ((3 4), (5 3), (...</code></pre>
<p>Alternatively, the function <code>st_crs</code> may be used extract coordinate system information from an sf-object:</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="spatial-data-structures.html#cb99-1" aria-hidden="true" tabindex="-1"></a>sf<span class="sc">::</span><span class="fu">st_crs</span>(point_sf_multi)</span></code></pre></div>
<pre><code>## Coordinate Reference System: NA</code></pre>
<p>In case when a CRS is missing or the wrong CRS is set, the function <code>st_crs</code> is used:</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="spatial-data-structures.html#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign WGS84 as CRS</span></span>
<span id="cb101-2"><a href="spatial-data-structures.html#cb101-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 4326 is the EPSG code of WGS84</span></span>
<span id="cb101-3"><a href="spatial-data-structures.html#cb101-3" aria-hidden="true" tabindex="-1"></a>sf<span class="sc">::</span><span class="fu">st_crs</span>(point_sf_multi) <span class="ot">&lt;-</span> <span class="dv">4326</span></span></code></pre></div>

<div class="rmdtip">
<p>EPSG-Codes of other reference systems can be found <a href="https://spatialreference.org/ref/epsg/?search=4326&amp;srtext=Search" target="_blank">here.</a></p>
</div>
<p>Now we transform the sf-object to <a href="https://spatialreference.org/ref/epsg/3416/" target="_blank">EPSG 3416</a> (Austrian Lambert Projection) with function <code>st_transform</code>:</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="spatial-data-structures.html#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign NAD27 as CRS</span></span>
<span id="cb102-2"><a href="spatial-data-structures.html#cb102-2" aria-hidden="true" tabindex="-1"></a>point_sf_multi_transform <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_transform</span>(point_sf_multi, <span class="dv">3416</span>)</span></code></pre></div>
<p>Eventually we can compare the two sf-objects with different coordinate systems:</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="spatial-data-structures.html#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)) <span class="co"># both plots together</span></span>
<span id="cb103-2"><a href="spatial-data-structures.html#cb103-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sf<span class="sc">::</span><span class="fu">st_geometry</span>(point_sf_multi_transform), <span class="at">main =</span> <span class="st">&quot;EPSG: 3416&quot;</span>)</span>
<span id="cb103-3"><a href="spatial-data-structures.html#cb103-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sf<span class="sc">::</span><span class="fu">st_geometry</span>(point_sf_multi), <span class="at">main =</span> <span class="st">&quot;EPSG: 4326&quot;</span>)</span></code></pre></div>
<p><img src="UNIGIS-AppDev-R_files/figure-html/unnamed-chunk-81-1.png" width="672" /></p>
<p>The same syntax and functions can be used to deal with <strong>line or polygon</strong> data. The following drop-downs contain two simple examples.</p>
<details closed>
<summary>
<ins>
<strong>Create Line Feature!</strong>
</ins>
</summary>
<p>
<p><i><font color="grey"></p>
<p>Lines are sequences of points. They’re instrumental in representing pathways, routes, or any linear feature. Here’s how you can create a line using <code>sf</code>:</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="spatial-data-structures.html#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a line from a matrix of coordinates</span></span>
<span id="cb104-2"><a href="spatial-data-structures.html#cb104-2" aria-hidden="true" tabindex="-1"></a>line <span class="ot">&lt;-</span> <span class="fu">st_linestring</span>(<span class="fu">matrix</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">3</span>, <span class="dv">2</span>))</span>
<span id="cb104-3"><a href="spatial-data-structures.html#cb104-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-4"><a href="spatial-data-structures.html#cb104-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to spatial feature</span></span>
<span id="cb104-5"><a href="spatial-data-structures.html#cb104-5" aria-hidden="true" tabindex="-1"></a>line_sf <span class="ot">&lt;-</span> <span class="fu">st_sf</span>(<span class="at">geometry =</span> <span class="fu">st_sfc</span>(line))</span>
<span id="cb104-6"><a href="spatial-data-structures.html#cb104-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-7"><a href="spatial-data-structures.html#cb104-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the line</span></span>
<span id="cb104-8"><a href="spatial-data-structures.html#cb104-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(line_sf)</span></code></pre></div>
<p><img src="UNIGIS-AppDev-R_files/figure-html/unnamed-chunk-82-1.png" width="672" /></p>
</font></i>
</p>
</details>
<details closed>
<summary>
<ins>
<strong>Create Polygon Feature!</strong>
</ins>
</summary>
<p>
<p><i><font color="grey"></p>
<p>Polygons are closed shapes, perfect for representing areas with defined boundaries. Here’s a demonstration using sf and its st_polygon function:</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="spatial-data-structures.html#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a matrix of coordinates</span></span>
<span id="cb105-2"><a href="spatial-data-structures.html#cb105-2" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>, <span class="dv">4</span>,<span class="dv">4</span>, <span class="dv">4</span>,<span class="dv">2</span>, <span class="dv">2</span>,<span class="dv">2</span>), <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb105-3"><a href="spatial-data-structures.html#cb105-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-4"><a href="spatial-data-structures.html#cb105-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a list of matrices (in this case, just one matrix)</span></span>
<span id="cb105-5"><a href="spatial-data-structures.html#cb105-5" aria-hidden="true" tabindex="-1"></a>list_of_coords <span class="ot">&lt;-</span> <span class="fu">list</span>(coords)</span>
<span id="cb105-6"><a href="spatial-data-structures.html#cb105-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-7"><a href="spatial-data-structures.html#cb105-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the polygon</span></span>
<span id="cb105-8"><a href="spatial-data-structures.html#cb105-8" aria-hidden="true" tabindex="-1"></a>polygon <span class="ot">&lt;-</span> <span class="fu">st_polygon</span>(list_of_coords)</span>
<span id="cb105-9"><a href="spatial-data-structures.html#cb105-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-10"><a href="spatial-data-structures.html#cb105-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to spatial feature</span></span>
<span id="cb105-11"><a href="spatial-data-structures.html#cb105-11" aria-hidden="true" tabindex="-1"></a>polygon_sf <span class="ot">&lt;-</span> <span class="fu">st_sf</span>(<span class="at">geometry =</span> <span class="fu">st_sfc</span>(polygon))</span>
<span id="cb105-12"><a href="spatial-data-structures.html#cb105-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-13"><a href="spatial-data-structures.html#cb105-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the polygon</span></span>
<span id="cb105-14"><a href="spatial-data-structures.html#cb105-14" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(polygon_sf)</span></code></pre></div>
<p><img src="UNIGIS-AppDev-R_files/figure-html/unnamed-chunk-83-1.png" width="672" /></p>
</font></i>
</p>
</details>

<div class="rmdexercise">
<p>The code above successfully creates and plots a polygon. However, imagine if the last coordinate in the coordinate matrix (2,2) was mistakenly omitted.</p>
<p>Consider the following questions:</p>
<ol style="list-style-type: decimal">
<li>What error would you expect to encounter if the last coordinate was omitted?</li>
<li>Why is the last coordinate crucial for the creation of the polygon?</li>
</ol>
<details closed>
<summary>
<ins>
<strong>Solution!</strong>
</ins>
</summary>
<p>
<p><i><font color="grey"></p>
<ol style="list-style-type: decimal">
<li>If the last coordinate was omitted, you would encounter the following error:</li>
</ol>
<p><code>Error in MtrxSet(x, dim, type = "POLYGON", needClosed = TRUE) : polygons not (all) closed</code></p>
<p>A breakdown of what the error message is conveying:</p>
<ul>
<li><p><code>MtrxSet(x, dim, type = "POLYGON", needClosed = TRUE)</code>: This is the internal function being called to set or validate the matrix representation of the polygon.</p></li>
<li><p><code>type = "POLYGON"</code>: This indicates that the data structure being worked on is in fact a Polygon.</p></li>
<li><p><code>needClosed = TRUE</code>: This is a condition set within the function to ensure that polygons are closed. It checks if the starting and ending coordinates of the polygon are the same.</p></li>
<li><p><code>polygons not (all) closed</code>: This is the main error message, indicating that one or more polygons in your data are not closed, i.e., their starting and ending coordinates don’t match.</p></li>
</ul>
<p>In practical terms, if you’re creating or manipulating polygons, you need to ensure that each polygon’s last coordinate is the same as its first coordinate. If not, many spatial operations, analyses, or visualizations might produce incorrect or unexpected results!</p>
<ol start="2" style="list-style-type: decimal">
<li>The last coordinate is crucial because it ensures that the polygon is closed, meaning its starting and ending coordinates are the same.</li>
</ol>
</font></i>
</p>
</details>
</div>
</div>
<div id="raster-data-structures" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Raster Data Structures<a href="spatial-data-structures.html#raster-data-structures" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Whereas man-made infrastructures (streets, buildings, sewage systems etc.) can clearly be delineated and modeled by discrete features, our natural-physical environment (temperature, soil moisture etc.) tends to be continuous by nature and best represented by raster data structures.</p>
<p>Both packages, <code>sf</code> and <code>terra</code> can handle raster and vector data. Due to its comprehensive toolset and integration with the tidyverse ecosystem (tidyverse will be covered in lesson Data Manipulation), <code>sf</code> is predominantly used for discrete vector data structures. Until quite recently, the package <a href="https://cran.r-project.org/web/packages/raster/index.html" target="_blank"><code>raster</code></a> has been the most popular resource to work with continuous data in R. This package is being replaced by <code>terra</code> (see <a href="https://psfaculty.plantsciences.ucdavis.edu/plant/AdditionalTopics_Transition.pdf" target="_blank">here</a> for more information).</p>
<p>Accordingly, in this chapter we will focus on the more modern <code>terra</code> package that offers several advantages over its predecessor:</p>
<ul>
<li>Efficiency: Terra is optimized for speed and uses less memory, making it more efficient for large datasets.</li>
<li>Flexibility: It supports raster, vector, and time-series data, providing a one-stop solution for various spatial data types.</li>
<li>Ease of Use: With a simplified and consistent syntax, terra is easier to pick up for newcomers.</li>
<li>Comprehensive Functions: From raster algebra to resampling and reclassification, terra offers a wide array of functionalities.</li>
<li>Integration: It’s designed to work seamlessly with other R packages, making it easier to integrate into larger workflows.</li>
</ul>
<div id="working-with-spatraster-objects" class="section level3 hasAnchor" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Working with SpatRaster objects<a href="spatial-data-structures.html#working-with-spatraster-objects" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <code>terra</code> <code>SpatRaster Object</code> can be created using function <code>rast</code>:</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="spatial-data-structures.html#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the terra package</span></span>
<span id="cb106-2"><a href="spatial-data-structures.html#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span>
<span id="cb106-3"><a href="spatial-data-structures.html#cb106-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-4"><a href="spatial-data-structures.html#cb106-4" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rast</span>()</span>
<span id="cb106-5"><a href="spatial-data-structures.html#cb106-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-6"><a href="spatial-data-structures.html#cb106-6" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## class       : SpatRaster 
## dimensions  : 180, 360, 1  (nrow, ncol, nlyr)
## resolution  : 1, 1  (x, y)
## extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
## coord. ref. : lon/lat WGS 84</code></pre>
<p>Per default the SpatRaster Object is initialized with a global extent and a spatial resolution of 1 degree. The coordinate reference system is WGS84.</p>
<p>Alternatively, additional arguments may be provided in the function to customize the SpatRaster Object:</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="spatial-data-structures.html#cb108-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">rast</span>(<span class="at">ncol=</span><span class="dv">100</span>, <span class="at">nrow=</span><span class="dv">100</span>, <span class="at">xmin=</span><span class="dv">797422</span>, <span class="at">xmax=</span><span class="dv">807387</span>, <span class="at">ymin=</span><span class="dv">5298037</span>, <span class="at">ymax=</span><span class="dv">5306341</span>, <span class="at">crs =</span> <span class="st">&quot;+proj=utm +zone=32 +ellps=WGS84 +datum=WGS84 +units=m +no_defs &quot;</span>)</span>
<span id="cb108-2"><a href="spatial-data-structures.html#cb108-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb108-3"><a href="spatial-data-structures.html#cb108-3" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## class       : SpatRaster 
## dimensions  : 100, 100, 1  (nrow, ncol, nlyr)
## resolution  : 99.65, 83.04  (x, y)
## extent      : 797422, 807387, 5298037, 5306341  (xmin, xmax, ymin, ymax)
## coord. ref. : +proj=utm +zone=32 +datum=WGS84 +units=m +no_defs</code></pre>
<p>In the example above, arguments such as the number of grid rows and columns (<code>nrow</code> and <code>ncol</code>) as well as the grid extent (<code>xmin</code>, <code>xmax</code>, <code>ymin</code> and <code>ymax</code>) were defined. The raster cell resolution is a result of these inputs (<code>x=99.65</code>, <code>y=83.04</code>).</p>
<p>According to the <a href="https://www.rdocumentation.org/packages/terra/versions/1.7-46/topics/rast" target="_blank">documentation of the <code>rast</code> function</a>, the coordinate reference system can be specified in <code>PROJ.4</code>, <code>WKT</code> or <code>authority:code</code> notation. In the given example <code>WGS84 UTM 33N</code> is encoded in <code>PROJ.4</code>. To find the desired encoding, it is recommended to first search for a CRS on the <a href="https://spatialreference.org/" target="_blank">Spatial Reference Website</a>. The <code>PROJ.4</code> is one out of many formats (e.g. EPSG code, WKT, GML etc.) that are provided in the search results.</p>

<div class="rmdexercise">
<p>The SpatRaster Object <code>x</code> has an extent that covers the City of Salzburg, which is completely within UTM Zone 33N. Search for the <code>PROJ.4</code> encoding of <code>WGS84 UTM 33N</code> on the <a href="https://spatialreference.org/" target="_blank">Spatial Reference Site.</a></p>
<details closed>
<summary>
<ins>
<strong>Solution!</strong>
</ins>
</summary>
<p>
<p><i><font color="grey"></p>
<p>+proj=utm +zone=33 +ellps=WGS84 +datum=WGS84 +units=m +no_defs</p>
</font></i>
</p>
</details>
</div>
<p>In order to change the coordinate reference system from <code>WGS84 UTM 32N</code> to <code>WGS84 UTM 33N</code> and to change the spatial resolution to 100m, the terra-functions <code>project</code> and <code>res</code> can be used:</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="spatial-data-structures.html#cb110-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">project</span>(x, <span class="st">&quot;+proj=utm +zone=33 +ellps=WGS84 +datum=WGS84 +units=m +no_defs&quot;</span>)</span>
<span id="cb110-2"><a href="spatial-data-structures.html#cb110-2" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">res</span>(y) <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb110-3"><a href="spatial-data-structures.html#cb110-3" aria-hidden="true" tabindex="-1"></a>y</span></code></pre></div>
<pre><code>## class       : SpatRaster 
## dimensions  : 91, 105, 1  (nrow, ncol, nlyr)
## resolution  : 100, 100  (x, y)
## extent      : 347863.1, 358363.1, 5291599, 5300699  (xmin, xmax, ymin, ymax)
## coord. ref. : +proj=utm +zone=33 +datum=WGS84 +units=m +no_defs</code></pre>
<p>Note that the number of rows and column was changed to enable a raster resolution of 100m. Also the bounding box coordinates of the SpatRaster Object have changed, which indicates a successful projection of the raster grid from <code>UTM 32</code> to <code>UTM 33</code>.</p>

<div class="rmdtip">
<p>Given that the SpatRaster Object has an undefined coordinate reference system, it can be defined by means of <a href="https://rdrr.io/cran/terra/man/crs.html" target="_blank">terra-function <code>crs</code></a>.</p>
</div>
<p>So far, we have created two SpatRaster Objects (identifiers x and y). They only consist of a skeleton, meaning that they have location, extend, a spatial gird resolution and a certain number of grid rows and columns. However, there are not yet cell-values associated with it:</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="spatial-data-structures.html#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="co">#check whether objects have values</span></span>
<span id="cb112-2"><a href="spatial-data-structures.html#cb112-2" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">hasValues</span>(x)</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="spatial-data-structures.html#cb114-1" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">hasValues</span>(y)</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p>The function <code>hasValues()</code> returns a logical value <code>FALSE</code>, because no values were assigned to objects <code>x</code> and <code>y</code>. The code below shows how to assign values to empty SpatRaster Object <code>y</code>:</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="spatial-data-structures.html#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="co">#assign random value between 0 and 1 to cells of SpatRaster Object y</span></span>
<span id="cb116-2"><a href="spatial-data-structures.html#cb116-2" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">values</span>(y) <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">runif</span>(terra<span class="sc">::</span><span class="fu">ncell</span>(y),<span class="dv">0</span>,<span class="dv">1</span>)</span>
<span id="cb116-3"><a href="spatial-data-structures.html#cb116-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb116-4"><a href="spatial-data-structures.html#cb116-4" aria-hidden="true" tabindex="-1"></a><span class="co">#get values with index 1 to index 5</span></span>
<span id="cb116-5"><a href="spatial-data-structures.html#cb116-5" aria-hidden="true" tabindex="-1"></a>terra<span class="sc">::</span><span class="fu">values</span>(y)[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div>
<pre><code>## [1] 0.5372985 0.3994123 0.7234440 0.5422059 0.6201349</code></pre>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="spatial-data-structures.html#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plot grid, plot() is a generic function to plot R objects</span></span>
<span id="cb118-2"><a href="spatial-data-structures.html#cb118-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(y, <span class="at">main=</span><span class="st">&#39;100m Raster, Salzburg&#39;</span>)</span></code></pre></div>
<p><img src="UNIGIS-AppDev-R_files/figure-html/unnamed-chunk-91-1.png" width="672" /></p>
<p>The function <code>runif</code> of package <code>stats</code> takes three arguments, <code>n</code>, <code>min</code> and <code>max</code>, to generate <code>n</code> random numbers in a range between <code>min</code> and <code>max</code>. In the example above argument <code>n</code> is derived from <code>terra</code> function <code>ncell</code>, which returns the number of cells of SpatRaster Object <code>y</code> as an integer value. As a result, we get a numeric vector of random values whose length corresponds to the number of grid cells of SpatRaster Object <code>y</code>. Accordingly, we can assign the numeric vector values to the grid.</p>

<div class="rmdexercise">
<p>When assigning or accessing values, it is crucial to know the origin and orientation of raster values. Create a SpatRaster Object with 4 cells and assign a numeric vector that consists of 4 values <code>c(1,2,3,4)</code> to it.</p>
<p>The syntax to select values from SpatRaster Objects is the same that we have use to select elements of matrix and array data structures:</p>
<p><code>raster-obj[&lt;row index&gt;, &lt;column index&gt;]</code></p>
<p>Where is the origin of the grid? In what order are the values <code>c(1,2,3,4)</code> stored in the vector grid?</p>
<details closed>
<summary>
<ins>
<strong>Solution!</strong>
</ins>
</summary>
<p>
<p><i><font color="grey"></p>
<p>r &lt;- terra::rast(ncol=2, nrow=2)<br />
terra::values(r) &lt;- c(1,2,3,4)<br />
plot(r)<br />
r[1,1]</p>
<p>r[1,1] returns value 1. Accordingly, the upper left corner is the origin of the SpatRaster Object. Values are stored left to right and top-down, i.e. r[2,2] returns value <code>4</code>.</p>
</font></i>
</p>
</details>
</div>
<p>Note that the layer number <code>lyr.1</code> is returned in the console, when accessing individual values of a SpatRaster Object. This implies that SpatRaster Objects can handle space-time and multivariable data. A useful example for integrating space and time in SpatRaster Objects is provided by Dominic Royé in his blog post <a href="https://dominicroye.github.io/en/2022/use-of-multidimensional-spatial-data/" target="_blank">Use of multidimensional spatial data.</a> For more sophisticated data cube applications, the use of the <a href="https://r-spatial.github.io/stars/" target="_blank">stars package</a> is recommended.</p>

<div class="rmdtip">
<p>In this lesson you learned to handle spatial vector and raster structures in R. To get to know these structures, we built vector and raster objects from scratch. In many instances, however, objects may be created in R by loading vector and raster file formats (e.g. .shp or .tif). This topic will be covered in lesson Read and Write Data.</p>
</div>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-structures.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="control-structures.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["UNIGIS-AppDev-R.pdf", "UNIGIS-AppDev-R.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
